language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: OhbIJFDS11T+b0k5EiPz7KgxOd0hLgmBJSxmFjwnFb4h2k7Iz71NwiXaNvRDKxGKBMejLrkCixuI/uPR5HlW8QgJOzB2QAKqVcDWbbx7z9fIJZrqHPqVMec4TVTwCC+uH5YtmQj3fANoDOO7gEh7jeF9atIdWWpwJcSMiQrQVPdrslhykGegO6BAeFhzna6r5vVg1vPbwEAMVXguHrs0Dx3JUhq5MbcrHfqFkri9QwacoCZ5tFiSk4wpzF//8lrgNLKsKnz5IFYRcLrjcTHHG92vFj4bj+TnEfm3sAPP1MEPUioqiwPAxV7+v/HhQUHiD85cfeXY4RLs+etu3VFVBOOxvTXpjClDmxN1pP5K/EC2SUM3/GCEcf2nTPEYumRCYd9GMzFu/cSGATBIdTUOT8TZQSfexax5NEYduVRJ7ZoKHcwTvV0e7gOJQo4SNtXNTSGqSGV4izxaq2nEAbOQlgqqaHgjz5AoMXapuGmRfsxzKu+0PvrAFLDf7A5lrcPp1dEmlJIDkZscQmznTQV4VIVAHzCnsaZ4QR5DnLJor/+8oWtQZhZ9vgdO6E7N68E/yqajS3bfK6E4sbbb6xI2ZZ8JSolPfNspp7Onwyt0+Jpf6gRL1A1xC0td57jGvjuKa9P88yo/1wFxSPBz+RYd2uzcYQ4oCON352p5GBajA7M=
  app: protected-plateau-70247
  on:
    repo: spokencode/node-shopping-list-integration-tests-ci
